//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptographyHelpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptographyHelpers.Resources.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication tag..
        /// </summary>
        internal static string Authentication_InvalidTag {
            get {
                return ResourceManager.GetString("Authentication.InvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input byte array cannot be null or empty..
        /// </summary>
        internal static string ByteArray_InvalidInputByteArray {
            get {
                return ResourceManager.GetString("ByteArray.InvalidInputByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key (null or wrong size)..
        /// </summary>
        internal static string Cryptography_InvalidKey {
            get {
                return ResourceManager.GetString("Cryptography.InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data succesfully decrypted..
        /// </summary>
        internal static string Decryption_DataDecryptionSuccess {
            get {
                return ResourceManager.GetString("Decryption.DataDecryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File succesfully decrypted..
        /// </summary>
        internal static string Decryption_FileDecryptionSuccess {
            get {
                return ResourceManager.GetString("Decryption.FileDecryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input bytes to decrypt required..
        /// </summary>
        internal static string Decryption_InputBytesRequired {
            get {
                return ResourceManager.GetString("Decryption.InputBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonce bytes required..
        /// </summary>
        internal static string Decryption_NonceBytesRequired {
            get {
                return ResourceManager.GetString("Decryption.NonceBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag bytes required..
        /// </summary>
        internal static string Decryption_TagBytesRequired {
            get {
                return ResourceManager.GetString("Decryption.TagBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found:.
        /// </summary>
        internal static string Directory_PathNotFound {
            get {
                return ResourceManager.GetString("Directory.PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data succesfully encrypted..
        /// </summary>
        internal static string Encryption_DataEncryptionSuccess {
            get {
                return ResourceManager.GetString("Encryption.DataEncryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File succesfully encrypted..
        /// </summary>
        internal static string Encryption_FileEncryptionSuccess {
            get {
                return ResourceManager.GetString("Encryption.FileEncryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input bytes to encrypt required..
        /// </summary>
        internal static string Encryption_InputBytesRequired {
            get {
                return ResourceManager.GetString("Encryption.InputBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:.
        /// </summary>
        internal static string File_PathNotFound {
            get {
                return ResourceManager.GetString("File.PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination file paths cannot be equal..
        /// </summary>
        internal static string File_SourceAndDestinationPathsEqual {
            get {
                return ResourceManager.GetString("File.SourceAndDestinationPathsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash computed succesfully..
        /// </summary>
        internal static string Hash_ComputeSuccess {
            get {
                return ResourceManager.GetString("Hash.ComputeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hash and verification hash does not match..
        /// </summary>
        internal static string Hash_DoesNotMatch {
            get {
                return ResourceManager.GetString("Hash.DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input bytes to compute hash required..
        /// </summary>
        internal static string Hash_InputBytesRequired {
            get {
                return ResourceManager.GetString("Hash.InputBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string to compute hash required..
        /// </summary>
        internal static string Hash_InputStringRequired {
            get {
                return ResourceManager.GetString("Hash.InputStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hash and verification hash does match..
        /// </summary>
        internal static string Hash_Match {
            get {
                return ResourceManager.GetString("Hash.Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification hash bytes required..
        /// </summary>
        internal static string Hash_VerificationHashBytesRequired {
            get {
                return ResourceManager.GetString("Hash.VerificationHashBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification hash string required..
        /// </summary>
        internal static string Hash_VerificationHashStringRequired {
            get {
                return ResourceManager.GetString("Hash.VerificationHashStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMAC computed succesfully..
        /// </summary>
        internal static string HMAC_ComputeSuccess {
            get {
                return ResourceManager.GetString("HMAC.ComputeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input bytes to compute/verify HMAC required..
        /// </summary>
        internal static string HMAC_InputBytesRequired {
            get {
                return ResourceManager.GetString("HMAC.InputBytesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input key string to compute/verify HMAC required..
        /// </summary>
        internal static string HMAC_InputKeyStringRequired {
            get {
                return ResourceManager.GetString("HMAC.InputKeyStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string to compute/verify HMAC required..
        /// </summary>
        internal static string HMAC_InputStringRequired {
            get {
                return ResourceManager.GetString("HMAC.InputStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification HMAC string required..
        /// </summary>
        internal static string HMAC_VerificationHMACStringRequired {
            get {
                return ResourceManager.GetString("HMAC.VerificationHMACStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key derived succesfully..
        /// </summary>
        internal static string KeyDerivation_DerivationSuccess {
            get {
                return ResourceManager.GetString("KeyDerivation.DerivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to derive key from password:.
        /// </summary>
        internal static string KeyDerivation_ExceptionError {
            get {
                return ResourceManager.GetString("KeyDerivation.ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bytes requested from key derivation required (must be greater than 0)..
        /// </summary>
        internal static string KeyDerivation_InvalidBytesRequested {
            get {
                return ResourceManager.GetString("KeyDerivation.InvalidBytesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid (and insecure) iteration count: Minimum must be greater or equal {0}..
        /// </summary>
        internal static string KeyDerivation_IterationCountInvalid {
            get {
                return ResourceManager.GetString("KeyDerivation.IterationCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password required for key derivation..
        /// </summary>
        internal static string KeyDerivation_PasswordRequired {
            get {
                return ResourceManager.GetString("KeyDerivation.PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base64 input string..
        /// </summary>
        internal static string Strings_InvalidInputBase64String {
            get {
                return ResourceManager.GetString("Strings.InvalidInputBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hexadecimal input string..
        /// </summary>
        internal static string Strings_InvalidInputHexadecimalString {
            get {
                return ResourceManager.GetString("Strings.InvalidInputHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string cannot be null, empty or white-space(s)..
        /// </summary>
        internal static string Strings_InvalidInputString {
            get {
                return ResourceManager.GetString("Strings.InvalidInputString", resourceCulture);
            }
        }
    }
}
