name: build-and-test
on: 
    push:
        branches:
            - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: dotnet build --configuration Release src/CryptographyHelpers/CryptographyHelpers/CryptographyHelpers.csproj

    - name: Run tests
      run: dotnet test src/CryptographyHelpers/CryptographyHelpers.Tests/CryptographyHelpers.Tests.csproj
